### ISSUE TITLE
Please help me to display the image in Readme.md

### ISSUE THREAD

**Issue by Bibekdhkl** [Bibekdhkl/Web-Development-Practises#1]
As I am giving a try to make a well-furnished readme.md file but  I am _stuck for 2 days_ in uploading the image.
Might be  I am puzzled in **keeping the path for the image in readme.md**

So I ### **will be more than grateful** if you could help me with this task.

**Comment by isarojdahal** [comment]
watch this brother, https://www.youtube.com/watch?v=0ZfDT2jlc9I

**Comment by Bibekdhkl** [comment]
@sarojdahal1213 I think the problem isn't fixed yet...
I having a problem in linking local photos so please could you suggest me sth more?

**Comment by isarojdahal** [comment]
it is the same as for external image.  ![alt text](location of your image)

**Comment by Bibekdhkl** [comment]
yeah, I got it...I was confused about ### image location
Previously, I kept local image location as in HTML linking by _/images/image_name.jpg_

But the actual way is like this:
`![alt text](https://github.com/[username]/[reponame]/blob/[branch]/image.jpg?raw=true)`

Here the path of Github location is to be provided rather than the local folder path.

**Comment by Bibekdhkl** [comment]
Thank you for your time.
